EspressoV2를 사용하지않고 트랜잭션 리스트 조회
elysia-dev/dutch pull request #32
Opened 2021-06-17 05:20 UTC by JUNG-gyucheol

## Etherscan / Bscscan API를 사용하여 트랜잭션 조회
- 이더스캔을 이용할 때는 kovan 테스트넷을 이용해서 트랜잭션을 조회했습니다.
- ERC20 / BNB 는 제 엘리시아 지갑주소를 이용하여 트랜재션을 조회했습니다.
- EspresssV2를 사용했을 때 가져오는 데이터와 동일해서 EspreesoV2 코드를 가져와서 url만 변경하였습니다.
~~~
export default class TransactionsAPIs {
  static getEthTransaction = async (
    address: string,
    page: number,
  ): Promise<AxiosResponse<CryptoTxsResponse>> => {
    return axios.get(
      `https://api-kovan.etherscan.io/api?module=account&action=txlist&address=${address}&startblock=0&endblock=99999999&page=${page}&offset=10&sort=desc&apikey=ASRYBDYSYS98VSJ2VMN65MXU2YWW982ABW`,
    );
  };

  static getErc20Transaction = async (
    address: string,
    tokenAddress: string,
    page: number,
  ): Promise<AxiosResponse<CryptoTxsResponse>> => {
    return axios.get(
      `https://api.etherscan.io/api?module=account&action=tokentx&contractaddress=0x2781246fe707bb15cee3e5ea354e2154a2877b16&address=0x85D268A0EBFdeA4F2906C45f402C4C5950767a03&page=${page}&offset=10&sort=desc&apikey=ASRYBDYSYS98VSJ2VMN65MXU2YWW982ABW`,
    );
  };

  static getBnbTransaction = async (
    address: string,
    page: number,
  ): Promise<AxiosResponse<CryptoTxsResponse>> => {
    return axios.get(
      `https://api.bscscan.com/api?module=account&action=txlist&address=0x85D268A0EBFdeA4F2906C45f402C4C5950767a03&startblock=1&endblock=99999999&page=1&offset=10&sort=desc&apikey=U63E7QAMMBVJW2C77C45F2IE8X21PN5A4G`,
    );
  };
}
~~~

- 위 에서만든 TransactionsAPIs 클래스를 가져와서 각각의 코인들을 클릭 했을 시에 타입에 맞게 실행됩니다. (ETH, BNB, ERC20)
~~~
    if (asset.type === CryptoType.ETH) {
        res = await TransactionsAPIs.getEthTransaction(address, state.page);
      } else if (asset.type === CryptoType.BNB) {
        res = await TransactionsAPIs.getBnbTransaction(address, state.page);
      } else {
        res = await TransactionsAPIs.getErc20Transaction(
          address,
          EL_ADDRESS,
          state.page,
        ); 
~~~

2021-06-17 13:50 UTC, modonguk requested changes
첫 풀리퀘스트 축하드립니다!
코드 포맷의 경우 로컬셋팅이 조금 달라, 변경하지 않아도 되는 이력들이 커밋에 포함되어 있어 보입니다. 요런것 들은 차차 고쳐보고 prettier 설정을 조금 손봐야할것 같습니다. 
TransactionsAPIs는 utils에 따로 나누어서 구현한 것은 인상적입니다. 아마 재활용을 미리 생각하신거겠죠? 좋은 방법입니다. 조금 더 좋은 아이디어로, 둘 다 이더스캔이니 "이더스캔 클라이언트"로 정의해서 api 폴더에 모아 두면 좀 더 통일성있는 코드가 될것 같습니다. 
고생하셨습니다!

2021-06-17 13:50 UTC, modonguk commented on src/modules/crypto/Detail.tsx
> +  );
network와 apiKey는 `.env`파일에 넣고 사용하는게 좋을 것이 좋습니다.
apiKey가 노출되면 더 쉽게 api 호출 제한에 걸릴 수 있습니다. 
network는 ETH_NETWORK으로 미리 정의해서 사용하므로, react-native-dotenv에서 불러오면되고,
ethscan key는 따로 결제해서 사용하도록 하죠. 개발환경에서의 api key는 개인것으로 우선 사용해주세요~

2021-06-17 13:50 UTC, modonguk commented on src/utiles/getTansections.ts
> +      `https://api-kovan.etherscan.io/api?module=account&action=txlist&address=${address}&startblock=0&endblock=99999999&page=${page}&offset=10&sort=desc&apikey=ASRYBDYSYS98VSJ2VMN65MXU2YWW982ABW`,
production환경에서는 kovan이 아니라 ethereum mainnet을 사용해야합니다. dotenv에 따라 다른 값을 가지도록 변경해주세요

2021-06-17 13:50 UTC, modonguk commented on src/utiles/getTansections.ts
> +      `https://api.etherscan.io/api?module=account&action=tokentx&contractaddress=0x2781246fe707bb15cee3e5ea354e2154a2877b16&address=0x85D268A0EBFdeA4F2906C45f402C4C5950767a03&page=${page}&offset=10&
ERC20의 경우,
개발 또는 스테이징 환경에서는 kovan 네트워크를 참조해야하고 프로덕션에서는 mainnet을 호출해야합니다. 둘다 dotenv의 ETH_NETWORK로 정의 되어있으니 확인해주세요. contractAddress또한 dotenv에 정의되어있고 배포하는 환경에 따라 그 값이 다릅니다.

2021-06-17 13:50 UTC, modonguk commented on src/utiles/getTansections.ts
> +      `https://api.bscscan.com/api?module=account&action=txlist&address=0x85D268A0EBFdeA4F2906C45f402C4C5950767a03&startblock=1&endblock=99999999&page=1&offset=10&sort=desc&apikey=U63E7QAMMBVJW2C77C4
여기도 마찬가지로, 
개발 & 스테이징환경에서는 testnet을 프로덕션에서는 mainnet을 참고해야합니다. 
따로 환경변수로 만들고 관리해주세요~

2021-06-22 08:48 UTC, JUNG-gyucheol commented on src/modules/crypto/Detail.tsx
> +  );
-  .env파일 넣어서 들고오도록 수정했습니다.
- 배포모드일때는 개인키를 사용하여 .env파일에 넣어두었습니다.
~~~
const provider = new ethers.providers.EtherscanProvider(
  ETH_NETWORK,
  ETHERSCAN_API,
);
~~~

2021-06-23 06:00 UTC, modonguk requested changes
코드확인했습니다. 논리적으로는 크게 벗어나는 것은 없는 것 같습니다.
유지보수를 더 잘할 수 있도록, 더 이해하기 쉬운 코드로 작성해주세요~
리팩토링만 마무리하면 될 것 같습니다!
얼른 그래프가 앱에 배포되면 좋겠군요 ㅎ ㅎㅎ

2021-06-23 06:02 UTC, modonguk commented
또한, 특이한 사항이 있는 코드들을 제외하고 작업물을 전부 풀리퀘스트 내용에 포함시키지 않아도됩니다! 
코드를 어차피 다 읽어보기 때문에, 핵심사항들만 내용으로 요약해주시면 더 좋을 것 같습니다 :)

2021-06-23 06:03 UTC, modonguk commented
앗 그리고 또 한가지! 새로 추가한 환경변수들은 모두 REAEME에 추가해주세요~

2021-06-24 09:56 UTC, JUNG-gyucheol commented on src/utiles/getTransactionChart.ts
> +    }
네 그부분은  아래처럼 수정하였습니다. 
배열변수에 넣어주고 forEach를 이용할때 배열변수가 필요했었는데 forEach문에서 파라미터로 array 지원해주는걸 알게 되었습니다.
~~~
await this.getTransactionData(...).data.result
        .map(...).forEach((tx, idx, arr) => {....}
~~~

2021-06-24 10:11 UTC, JUNG-gyucheol commented
# getTransactionChart.ts 파일 수정
-  getTransactionChart.ts  ->  ChartTransactions.ts로 수정
- ChartTransactions 클래스로 만들었습니다.
- address, 현재 가지고있는 토큰,assetType 클래스 생성자로 바로 넣어줬습니다. 그래프가 바뀌더라도 바뀌지 않는 고정적인 값이라 생각하여 보유수량 페이지로 들어왔을 때 바로 객체를 생성하도록 해놓았습니다.

# 차트 수정
- CustomChartTooltip 컴포넌트를 사용하지 않고 따로 컴포넌트를 만들었습니다(ClickChartLine.tsx). 표시되는게 그래프로 기준으로 표시가 되어서 클릭했을때 라인과   텍스트가 고정이 되지않습니다.

2021-06-25 04:16 UTC, modonguk approved these changes
ChartTransactions class가 인상적입니다. 비슷한 기능을 하는 함수들을 묶어서 사용하기 좋게 만드셨군요!
1~4와 같은 숫자를 enum type으로만 변경해서 작업 후 머지해주세요.
고생하셨습니다. :)

2021-06-25 04:16 UTC, modonguk commented on AppMain.tsx
> +                <ChartDataProvider>
나중에 ChartDataProvider의 위치를 고민해보면 좋을것 같긴합니다.
chart data가 쓰일 수 있는 곳은 한곳뿐이라, 요렇게 다 provider로 만들고 상태를 다 내려주는게 맞을지 의문이긴 합니다.
그렇지만 우선 여기는 이렇게 남겨두도록 하죠

2021-06-25 04:16 UTC, modonguk commented on src/modules/crypto/components/SelectBox.tsx
> +    if (selectType === 'day') {
selecteType이랑, borderBottomColor가 return하는 1~4의 숫자는 타입스크립트의 Enum으로 관리하면 더 알아보기 쉬울것 같습니다.

2021-06-25 05:43 UTC, JUNG-gyucheol commented on AppMain.tsx
> +                <ChartDataProvider>
네 알겠습니다! useState로도 충분히 사용가능하다고 생각하여서 provider를 지우고 useState로 수정하였습니다.

2021-06-25 05:44 UTC, JUNG-gyucheol commented on src/modules/crypto/components/SelectBox.tsx
> +    if (selectType === 'day') {
제가 selectType Enum 과 ChartTabDays Enum 파일을 만들었습니다.

2021-06-25 06:07 UTC, merged

2021-06-25 06:27 UTC, modonguk commented
고생하셨습니당ㅎㅎ