Fix/usability
elysia-dev/dutch pull request #34
Opened 2021-06-28 07:20 UTC by leegakyeong

### 한 일
1. 하단 내비게이션 탭을 옮겨다닐 때마다 뜨던 ajax 관련 워닝이 뜨지 않도록 했습니다. 
2. 안드로이드에서 스토리 카드를 누를 때 애니메이션이 버벅이는 문제를 해결했습니다. 처음에는 안드로이드에서만 `react-native-reanimated` 라이브러리를 사용하려고 했는데, 이미지가 깜박이는 문제를 해결하지 못 해서... reanimated 라이브러리를 사용하지 않는 대신 css transform 속성에 애니메이션을 적용하는 방향으로 다시 구현했습니다. 

### 궁금한 점
* react-native-reanimated를 사용해서 구현했던 커밋은 기록에서 지우고 풀리퀘스트를 보내는 것이 나을까요?

2021-06-28 08:39 UTC, leegakyeong commented
앗 iOS에서 약간 문제가 있어서 다시 살펴보겠습니다!

2021-06-28 10:43 UTC, modonguk requested changes
작업내용 확인했습니다! 
애니메이션 사용시, top bottom 사용보다 translate를 사용하면 cpu 사용 절약? 에 관한 레퍼런스 코멘트에 달아주세요. 말씀하신것 처럼 사용하지 않는 라이브러리는 풀리퀘스트에 포함시키지 않는게 좋습니다. git 명령어를 연습해볼 겸, [interactive rebase](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history)를 이용해서 브랜치를 리베이스하고 다시 풀리퀘를 열어보는건 어떨까요?!

2021-06-28 10:43 UTC, modonguk commented on src/modules/products/components/ExpandedCard.tsx
> +  const finalSize = {
finalSize는 이 컴포넌트 범위에서 선언하지 않고, useEffect 안에서만 선언하고 사용해도 좋을 것 같아요!

2021-06-29 04:43 UTC, modonguk approved these changes
네 확인했습니다. 머지해도됩니다!

2021-06-29 04:54 UTC, leegakyeong commented
넵 리베이스는 다음부터 시도해 볼게요. 그리고 아침에 데일리스크럼 때 말씀드렸던 '지갑 삭제하기' 문구 수정 관련한 것들도 다음 풀리퀘스트에 포함시키도록 하겠습니다~~!

2021-06-29 04:54 UTC, merged