구매/환불 페이지 UX/UI 개선 & Allowance check 구현
elysia-dev/dutch pull request #37
Opened 2021-07-09 09:45 UTC by leegakyeong

# 한 일
### 구매/환불 페이지 UX/UI 개선
1. 구매/환불 전에 건물 이름, 구매 금액 등을 마지막으로 확인할 수 있는 모달창 추가
2. 한국어, 영어, 중국어 i18n 텍스트 추가
3. 금액 입력을 가상화폐가 아니라 달러로 입력하도록 변경
4. TxInput에서 입력한 값과 가스비 등을 보여 주는 TxInputViewer, $1/$100 등의 값을 간편하게 입력할 수 있는 NumberPadShorcut을 별도의 컴포넌트로 분리
5. 건물 토큰 이름을 ELA ->ELA4와 같은 식으로 보여주도록 변경
### Allowance check 구현
1. 첫 사용자의 경우 모달창에서 allowance check를 하도록 버튼 제공
# 할 일
1. 숫자 입력 키패드에서 지우기 버튼을 계속 누르고 있으면 숫자가 연속적으로 지워지도록 하는 기능은 구현하기가 생각보다 복잡한 것 같아서 일단 제외 ㅜㅜ
# 테스트
1. allowance check 버튼을 눌러서 버튼이 구매하기 버튼으로 잘 바뀌는지 확인
2. 구매/환불 페이지에서 받는토큰/금액입력 탭을 오갈 때 입력값이 서로 잘 변환되는지 확인
3. NumberPadShortcut 버튼을 눌렀을 때 값이 잘 입력되는지 확인
4. 내 자산과 건물리스트 모두에서 건물을 문제 없이 구매/환불할 수 있는지 확인
5. ETH/EL/BNB 등 모든 타입의 건물을 문제 없이 구매/환불할 수 있는지 확인
6. 한국어/영어/중국어로 각각 설정했을 때 문구가 너무 길어져서 잘리는 등 디자인적인 측면에서 거슬리는 것이 없는지 확인

2021-07-11 10:28 UTC, donguks requested changes
코드 잘보았습니다!
from, to를 예전에 잘못 작성해두어서 고생이 많습니다 ㅜㅜ
이번 기회에 바꿀 수 있으면 바꿔도 좋을 것 같아요!
코드 곳곳에 let으로 선언하고, if, else 조건문으로 작성한 코드가 많았는데 요런 코드들은 대부분 삼항연산자로 더 쉽게 작성할 수 있습니다. 
또한 색상값의 경우 Enum에 추가해주시면 좋을것 같습니다. (이름에 규칙이 없긴 하지만, 미리 enum으로 선언해두면 재활용하기도 좋고 나중에 한번에 바꾸기도 편합니다.)
우선 이번 코드 리뷰는 거의 형식? 코드 가독성에 초점을 맞추어 보았습니다. 
논리적 오류?는 코드로 확인하는 것보다 실제로 테스트를 진행해보는게 더 빠를것 같아서요!

2021-07-11 10:28 UTC, donguks commented on src/modules/asset/components/TxInputViewer.tsx
> +const Label: React.FC<LabelProps> = ({
Label, LabelInvalid등은 이 컴포넌트 안에서만 쓰이긴 하지만, 따로 component로 분리해두는게 코드 가독성면에서 더 나을것 같습니다.

2021-07-11 10:28 UTC, donguks commented on src/modules/asset/components/TxInputViewer.tsx
> +    valueText = (
여기도 따로 컴포넌트로 만들어 두는게 더 좋을 것 같아요!

2021-07-11 10:28 UTC, donguks commented on src/modules/products/ProductBuying.tsx
> +          value: state.product?.totalValue, // 이것도 필요하던가... 아니 근데 이걸 나중에 잔고로 쓰기도 함....?ㅠㅠ
ㅜㅜ 코멘트가 마음이 아프군요
TxInputViewer.tsx에서 쓰이는 from, to와 타입이 비슷하다면 같이 아예 type을 만들어도 좋을 것 같습니다.
(제가 미리 타입으로 만들어 두었어야했는데.. 죄송합니다)

2021-07-11 10:28 UTC, donguks commented on src/shared/components/NumberPad.tsx
> +const DialButton: FunctionComponent<{ pressHandler: () => void, value?: string, img?: any }> = ({
img는 string?으로 받아도 되었던 걸로 기억합니다. 
음 근데 차라리, DialButton이라는 이름을 꼭 써야하는 고집을 버리면, img를 인자로 넣어주지 않아도 되고 child를 선언하지 않아도 될것 같아요. 단순히 TouchableHighlight를 재활용하기 위해서 포기하는게 너무 많아 보입니다.

2021-07-11 10:28 UTC, donguks commented on src/shared/components/NumberPad.tsx
> +const DialButton: FunctionComponent<{ pressHandler: () => void, value?: string, img?: any }> = ({
ㅋㅋㅋ 하는김에 다른 컴포넌트로 파일을 분리해도 너무 좋을 것 같습니다.

2021-07-11 10:28 UTC, donguks commented on src/utiles/decimalFormatter.ts
> +const decimalFormatter = (num: number, place: number) => {
decimalFormatter 이 함수의 역할은 무엇인가요?!
대부분의 format은 javascript의 Intl.NumberFormat을 사용해주면 편합니다. !
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

2021-07-11 10:28 UTC, donguks commented on src/modules/asset/components/TxInputViewer.tsx
> +  return (
return 문안에 코드가 간단해보여서 자칫, 코드 가독성이 높아졌다고 생각할 수 있으나, 
변수를 많이 선언하면 오히려 더 읽기 어려운 코드가 됩니다. 
이 변수가는 무엇이지? 변수가 하는 역할이 무엇이지? 왜 이변수는 이 이름일까?"라는 고민을 코드를 읽으면서 계속해야하기 때문입니다.
case가 정말 많은 경우가 아니라면, 이 정도는 return문안에 삼항연산자로 코드를 작성해도 충분히 이해하기 쉬운 코드라고 생각합니다.

2021-07-12 00:48 UTC, leegakyeong commented on src/modules/asset/Purchase.tsx
> +            value: utils.parseEther(ether).toHexString(),
이 부분하고 이 위에서 가스비 추정할 때도 toHexString()을 쓰고 있어서 그것도 삭제했습니다! 테스트도 완료했습니당 b605af3

2021-07-12 01:01 UTC, leegakyeong commented on src/modules/asset/components/NumberPadShortcut.tsx
> +  setValues: any // 이름에 value가 너무 많이 들어가서 좀 헷갈리긴 한다... 그리고 타입도 좀 엄밀하게
TxInput.tsx에서도 저기랑 똑같이 props로 setValues()를 넘겨받는데 거기서는 
```js
setValues: Dispatch<SetStateAction<{ from: string; to: string; }>>
```
이런 식으로 정의해 주고 있더라고요. 그래서 이거랑 똑같이 해 봤는데 이건 어떠신가요?!

e4ec142

2021-07-12 01:06 UTC, donguks commented on src/modules/asset/components/NumberPadShortcut.tsx
> +  setValues: any // 이름에 value가 너무 많이 들어가서 좀 헷갈리긴 한다... 그리고 타입도 좀 엄밀하게
좋습니다!

2021-07-12 01:11 UTC, leegakyeong commented on src/modules/asset/components/NumberPadShortcut.tsx
> +  const buttons = [];
헉 아주좋습니다!! 0a9cd11

2021-07-12 01:13 UTC, leegakyeong commented on src/modules/asset/components/NumberPadShortcut.tsx
> +  function addValue(value: number) { console.log(inputValue)
126afc6

2021-07-12 01:43 UTC, leegakyeong commented on src/modules/asset/components/TxInput.tsx
> +  purpose: string
넵! 나중에 출금할 때도 새로 만든 이 enum에 추가할 수 있을 것 같네용 65f0d12

2021-07-12 01:53 UTC, leegakyeong commented on src/modules/asset/components/TxInput.tsx
> +        {input}
9ecb774

2021-07-12 02:44 UTC, leegakyeong commented on src/modules/asset/components/TxInputViewer.tsx
> +    valueText = (
9a02b42

2021-07-12 02:44 UTC, leegakyeong commented on src/modules/asset/components/TxInput.tsx
> +      <Modal
9a02b42

2021-07-12 03:14 UTC, leegakyeong commented on src/modules/asset/components/TxInputViewer.tsx
> +const Label: React.FC<LabelProps> = ({
3aaac73

2021-07-12 03:58 UTC, leegakyeong commented on src/modules/asset/components/TxInputViewer.tsx
> +    valueText = (
valueText와 balanceText를 합쳐서 LargeTextInput이라는 컴포넌트로 빼 놓았습니다! 0c7a473

2021-07-12 04:10 UTC, leegakyeong commented on src/modules/asset/components/TxInputViewer.tsx
> +  return (
3959d27

2021-07-12 04:31 UTC, leegakyeong commented on src/utiles/decimalFormatter.ts
> +const decimalFormatter = (num: number, place: number) => {
헐헐 저런 게 있는 줄 몰랐네요!!!! decimalFormatter는 Intl.NumberFormat의 maximumFractionDigits 옵션이 하는 일을 하려고 짰던 함수입니다! ㅋㅋㅋ Intl.NumberFormat을 쓰면 commaFormatter와 currencyFormatter 함수도 대체할 수 있을 것 같네요. 일단은 제가 짰던 부분만 수정해 놓겠습니다

2021-07-12 04:46 UTC, leegakyeong commented on src/utiles/decimalFormatter.ts
> +const decimalFormatter = (num: number, place: number) => {
근데 살펴보니 decimalFormatter, commaFormatter, currencyFormatter 함수가 number와 string 타입을 오가면서 복잡하게 얽혀 있어서  Intl.NumberFormat을 도입하는 건 이번 배포에 꼭 포함시킬 필요는 없을 것 같습니다! 지금 쓰는 함수들도 가벼운 것들인 것 같고(아마도..?) commaFormatter, currencyFormatter는 꽤 오래 전부터 여러 군데에서 쓰이고 있던 것 같아서요. value라는 이름이 들어가는 변수들의 타입을 number로 통일하고 사용자에게 보여줄 때만 string으로 바꾸는 작업도 나중에 Intl.NumberFormat을 도입하면서 같이 하면 좋을 것 같습니다. 근데 오늘 안에 하기는 힘들 것 같아요!!ㅠㅠ 일단 다른 것부터 하고 시간이 있는지 살펴보겠습니다...

2021-07-12 05:30 UTC, leegakyeong commented on src/modules/asset/components/TxInput.tsx
> +  let fromBalance = 0;
'purchase, refund, interest에 각각 맞는 balance를 지정해주는 코드' 이게 purposeType을 말씀하시는 거 맞나요?? 이건 지금 구매하기와 환불하기를 코드에서는 purchase/refund로 구분하는데 i18n을 쓰기 위한 json에서는 invest/refund로 구분하는 것 같아서 템플릿 문자열에 바로 집어넣으려고 만든 변수입니다! 나중에 invest/refund를 purchase/refund라고 바꾸면 코드가 간단해질 것 같긴 한데, 아직 다른 페이지들에서는 '투자'라는 말을 쓰고 있는 것 같아서 일단 저렇게 뒀습니다. 
그리고 '아래의 변수들'이라는 건 혹시 어떤 것들을 말씀하시는 건지 다시 설명해 주실 수 있나요?!

2021-07-12 05:32 UTC, leegakyeong commented on src/shared/components/NumberPad.tsx
> +const DialButton: FunctionComponent<{ pressHandler: () => void, value?: string, img?: any }> = ({
숫자나 소수점을 입력하는 버튼을 DialButton으로, 입력한 숫자를 지우는 버튼을 RemoveButton으로 분리했습니다! bc2b985

2021-07-13 01:09 UTC, leegakyeong commented on src/modules/asset/Purchase.tsx
> +      const ether = String(parseFloat(values.from) / getCryptoPrice(from.type)) // dollar to crypto
17cc3bb

2021-07-13 02:20 UTC, donguks commented on src/modules/asset/components/TxInput.tsx
> +  let fromBalance = 0;
아래의 변수들이란, fromBalance와 toBlance입니다 ㅋㅋ
요 변수들을 컴포넌트의 props로 만들어 두면, purpose로 조건을 확인하지 않아도됩니다.
조금 더 유연한 TxInput 컴포넌트를 만들 수 있습니다.

2021-07-13 02:25 UTC, donguks commented on src/utiles/decimalFormatter.ts
> +const decimalFormatter = (num: number, place: number) => {
넵!
commaFormatter, curencyFormatter 모두 청산해야할 기술부채입니다. 그렇지만 그렇게 큰 부채대상은 아닙니다 ㅜ 단순히 작업이 Intl.NumberFormat을 사용하는 것이기 때문이죠.
다만 currencyFormatter의 경우 Intl을 사용해도되나, 유저가 사용하고 있는 언어로 Formatter을 만들어줘야해서 Context-Provider 형태로 만들기는 했는데 어떤 페이지에서는 소수점을 몇자리까지 표현해야하는 등의 제약도 많아서 과연 이 방법이 맞았는지는 의문입니다.
어떤 형태가 나을지 고민하고 이 부분도, 이번 리팩토링 기간?에 넣어보면 좋을 것 같습니다.

2021-07-13 03:21 UTC, leegakyeong commented on src/modules/products/ProductBuying.tsx
> +          value: state.product?.totalValue, // 이것도 필요하던가... 아니 근데 이걸 나중에 잔고로 쓰기도 함....?ㅠㅠ
이것도 일단 다음 스프린트로 넘기겠습니다!

2021-07-13 03:53 UTC, leegakyeong commented on src/modules/asset/components/TxInput.tsx
> +  let fromBalance = 0;
9e0903e

2021-07-13 07:07 UTC, JUNG-gyucheol commented
가경님이 commit하신 코드 잘 봤습니다. 저도 아직 가경님이 구현하신 로직에 대해 잘 알지못해서 이번에는 코드리뷰가 어려울 것 같습니다.
commit으로 로그를 분리해서 남기신거 너무 잘하신 것같아서 보고 배우네요. 그리고 eslint 도입은 이번 스프린트때부터 바로 하면 좋다고 생각합니다. 제가 가경님한테 배워야 될 게 많다고 생각이 드네요.

2021-07-13 07:54 UTC, merged