메타마스크 & 아이토큰 앱 연동 / BNB로 구매한 상품 표시
elysia-dev/dutch pull request #38
Opened 2021-07-09 12:12 UTC by JUNG-gyucheol

### 메타마스크 & 아임토큰 연동
-  메타마스크에서 espresso api를 거치지않고 url로 hazelnut으로 정보를 전달
### BNB로 구매한 상품 표시
- loadv1user 와 loadv2user 를 하나의 함수로 실행하도록 수정
- 구매한 상품 트랜잭션 조회 할 때 espresso를 이용하지 않고 etherscan api를 이용하여 바로 조회
- 구매한 상품을 트랜잭션 조회하는 함수도 lagacy 상품은 ownershipId로 판단하여 트랜잭션 조회할 수 있도록 수정
- 더 보기 버튼눌렸을 시에 똑같은 트랜잭션이 조회가 되어서 수정
### 테스트시 문제점
-  api를 이용하다보니 동시에 조회를 하니 하나는 조회되고 다른 것들은 서버에러 발생

2021-07-11 11:57 UTC, donguks requested changes
코드 잘 확인했습니다!

아쉬운 점은,
1) 단순 코드 포맷팅 내용이 커밋에 포함되어 어떤것이 실제로 작업한 내용인지 구분하기 어렵다는 점 2) 커밋 로그가 하나도 분리되어있지 않다는 점입니다.
코드 리뷰를 할때, 정확히 어떤 내용이 바뀐지만 확인할 수 있으면 다음 번 리뷰는 좀 더 쉽게 할 수 있을 것 같습니다. 커밋에 정확한 변경사항만 포함하도록 더 신경써주세요!

2021-07-11 11:57 UTC, donguks commented on src/providers/AssetProvider.tsx
> +              wallet?.getFirstAddress() || address,
`wallet?.getFirstAddress() || address` 부분은 모두 address로 변경해도 같은 표현입니다.

2021-07-11 11:57 UTC, donguks commented on src/modules/asset/Detail.tsx
>      const userAddress = wallet?.getFirstNode()?.address || '';
userAddress에 `|| ethAddress`를 추가해서 재활용하는것은 어떨까요?

2021-07-11 11:57 UTC, donguks commented on src/modules/asset/Detail.tsx
>    const loadV2Detail = async () => {
이제는 loadV2Detail일 필요가 없어보입니다. 이름을 단순하게바꿔도 좋을 것 같아요.

2021-07-11 11:57 UTC, donguks commented on src/modules/asset/Detail.tsx
> +        const userAddress =
자주 반복되는 것 같은데, 아예 변수로 밖에 선언해두어도 좋을 것 같습니다.

2021-07-11 11:57 UTC, donguks commented on src/modules/asset/components/PaymentSelection.tsx
> +          `imtokenv2://navigate?screen=DappView&url=https://${DAPP_URL}/requests/${productId}/${valueTo}/${type}/${contractAddress}/${user.ethAddresses}/${user.language}`,
주소는 '/'로 구분하는 것보다 [Query string](https://en.wikipedia.org/wiki/Query_string)을 사용해서 순서를 지키지 않도록 구현하는게 더 좋습니다.

2021-07-11 11:57 UTC, donguks commented on src/modules/dashboard/Main.tsx
> +    await refreshUser();
wallet유저의 경우 refreshUser를 하지 않아도 되는데, 해주는 이유는 무엇인가요?!

2021-07-12 11:50 UTC, JUNG-gyucheol commented on src/utiles/LoadLagacyDetail.ts
> +  legacyTxToCryptoTx(tx: Transaction): CryptoTransaction {
v1 과 v2를 사용했던 것들을 한 클래스안에 넣어서 가져오도록 구현했습니다.

2021-07-12 11:58 UTC, JUNG-gyucheol commented on src/modules/dashboard/Main.tsx
> +    await refreshUser();
제가 잘못알았네요 refreshUser는 lagacy 상품을 가지고 있는 사람들의 데이터를 가져와야하기 때문에 지갑유저는 필요없었네요.

2021-07-12 12:03 UTC, JUNG-gyucheol commented
죄송합니다. 아직 깃허브 사용하는 데에 미숙하여 다음 스프린트부터는 어떤 하나의 작업을 끝낸  뒤 커밋을 분리하여 로그를 남기겠습니다.

2021-07-13 02:56 UTC, leegakyeong commented
저도 규철님 코드 한 번 쭉 읽어봤습니다! 제가 담당한 적이 없는 코드가 대부분이라 당연하지만 로직?에 대해서 코멘트를 드리기는 어려울 것 같아요. 다음 스프린트에서 서로 역할을 바꿔서 개발하면 그 다음 스프린트에서는 그런 부분들도 리뷰를 해 드릴 수 있게 될 것 같습니다! 그래서 이번에는 코딩 컨벤션? 관련된 부분들에 대해서 일단 말씀드리려고 합니다. 코드 끝에 세미콜론을 붙인다거나, 모듈을 임포트할 때 하나 이상이면 줄바꿈을 한다든지 이런 것들은 지금 봤을 때 파일마다도 규칙이 다르고 저랑 규철님도 조금씩 다른 것 같거든요. 그래서 보니까 모도리 노션 페이지에서 Development/Wiki/Frontend 페이지 보면 ESlint & Prettier 세팅에 관한 부분이 있더라구요. 저는 인턴 시작하고 쓴 적이 없긴 한데 ㅋㅋㅋ 이거를 다시 적용하면 좋을 것 같아요! 평소에 개발할 때는 코딩컨벤션에 신경 쓰지 말고 하다가 개발 다 끝나면 따로 한꺼번에 ESlint 돌리고 별도의 커밋으로 분리하면 같은 파일을 수정하더라도 충돌날 일도 덜할 것 같아요! 혹시 ESlint 도입에 대해서 어떻게 생각하시나요??

2021-07-13 05:46 UTC, JUNG-gyucheol commented
가경님 코드리뷰 감사합니다! ESlint 도입은 좋다고 생각합니다. 조금 더 코드 가독성도 좋아보일거고 이번 스프린트부터 도입해봐도 괜찮을거라고 생각합니다!

2021-07-13 07:48 UTC, leegakyeong commented
아 규철님 코드가 아니라 지금 더치 프로젝트가 전체적으로 그렇다는 뜻이었어요! 저는 그래서 그냥 작업하는 파일에 맞춰서 코드 작성했었는데 규철님은 오히려 뭔가 스스로 지키려는 코딩 컨벤션?이 있으신 것 같아서 ESlint 같은 걸 써야겠다는 생각이 났어요 ㅋㅋㅋ 아무튼 그래서 저희 풀리퀘스트 둘 다 머지되고 나면 먼저 ESlint 한 번 돌린 다음에 다시 master 브랜치에 머지하고, 그 다음에 다른 작업들 시작하면 될 것 같습니다!

2021-07-13 12:37 UTC, donguks approved these changes
고생하셨습니다! 
몇몇 리뷰는 적용이 안되긴 했지만, 우선 머지후 테스트하면서 고쳐봐도 좋을 것 같습니다.

2021-07-14 01:58 UTC, merged