가속화 기능 구현
elysia-dev/dutch pull request #53
Opened 2021-08-05 06:05 UTC by JUNG-gyucheol

## 가속화 기능 구현
1. 상품을 구매하거나 자산을 다른 유저한테 전송하면 거래기록에 펜딩중인 트랜잭션 표시
2. 가속화 버튼클릭시 가스가격을 조정 할 수 있는 모달창이 나옴
3. 가스가격은 전송할 때 보낸 가스가격보다 높게 입력하도록 설정 / 낮게 입력하면 버튼 비활성화
4. 가스가격 텍스트창 옆에 버튼 클릭시 가스가격이 '1 '씩 올라가도록 설정
5. 가스비(수수료)를 너무 높게 설정하여서 부족하면 버튼 비화설화

## 문제점
1. 로컬스토리지에 새로생성된 트랜잭션 하나만 들어가도록 구현하였습니다. 그래서 ETH 네트워크로 구매한 후(아직 계속 pending상태) BSC로 구매하면 로컬 스토리지에 BSC로 구매한 트랜잭션이 로컬스토리지에 들어가 ETH로 구매한 트랜잭션은 볼 수가 없음 ( 트랜잭션 실패 표시 구현 추가 후 수정을 해야 될 것 같습니다.)
2. 트랜잭션이 pending중인 상태에서 또 구매를 해버리면 앞에 생성된 트랜잭션은 사라지고 최근에 생성한 트랜잭션으로 변경되버리는 문제점이 있습니다. - 대기열 목록을 만들고 nonce를 설정해줘야 할 것 같습니다. 
예) nonce가 '158' 인 트랜잭션을 생성하면 pending 상태일텐데 다른 상품을 구매할 때 nonce를 '159' 를 주고 대기목록에 표시하는 방법 
( nonce: 158 트랜잭션이 완료되면 자동으로 nonce: 159 트랜잭션이 생성됨 )

2021-08-05 09:18 UTC, donguks reviewed
가속화 코드 작성한것 잘 확인했습니다!
브랜치 이름은 fix/error-message였지만.... 가속화로 작업이 변경되었네요 :)
고생하셨습니다! 몇가지 리팩토링 & 코드 개선 작업 진행하면 될것 같습니다!

2021-08-05 09:18 UTC, donguks commented on src/modules/asset/components/TransactionItem.tsx
> +              moment(transaction.createdAt).format('YYYY-MM-DD') +
오 이거 이제 봤는데
format('YYYY-MM-DD | HH:mm:ss') 로도 잘 작동할 것 같습니다!

2021-08-05 09:18 UTC, donguks commented on src/modules/asset/components/TransactionItem.tsx
> +      const isCrytoELA = paymentMethod !== 'NONE';
addPendingTransaction을 두번하는 이유가 있을까요?!

2021-08-05 09:18 UTC, donguks commented on src/modules/asset/Purchase.tsx
> +      console.log(txRes);
console은 지워주셔도 될것 같습니다~

2021-08-05 09:18 UTC, donguks commented on src/modules/asset/Purchase.tsx
> +      waitTxResult(contractAddress, 2); // status는 enum-pending으로 변경
이번 기회에 enum을 넣어보는건 어떨까요! waitTxResult의 상태값이 마음에 들지 않는군요 ㅜ

2021-08-05 16:25 UTC, JUNG-gyucheol commented on src/modules/asset/components/TransactionItem.tsx
> +      const isCrytoELA = paymentMethod !== 'NONE';
자산상세페이지에서 구매하거나 전송하면 펜딩중인 상태만 볼 수 있어서 트랜잭션이 성공했을 때 바로 성공한 트랜잭션을 바로 볼 수 없다고 생각해서  두번 호출했습니다.

2021-08-05 16:52 UTC, JUNG-gyucheol commented on src/utiles/pendingTransaction.ts
> +export const getPanadingTx = (
- 로컬스토리지에 저장된 펜딩중인 트랜잭션 리턴 / 펜딩중인 트랜잭션이 성공한 트랜잭션한 있는지 없는지를 boolean으로 리턴합니다.
- 자산상세페이지로 들어갔을 때 transaction을 load할 때 pending 중인 트랜잭션이 있는지 없는지 판단하여 표시하는 역할을 합니다.

2021-08-05 17:02 UTC, JUNG-gyucheol commented on src/utiles/createTransction.ts
> +          : BigNumber.from('100'),
제가 테스트한다고 100으로 넣어줬네요.  undefined로 넘겨주니 에러 발생해서 가속화가 아닐 때는 gasprice를 넣어주려고 합니다!

2021-08-05 17:12 UTC, JUNG-gyucheol commented on src/enums/Accelerate.ts
> +  export default Accelerate
baae7f3a46bbfa911a49c581e86b47b8fd4bf938

2021-08-05 17:13 UTC, JUNG-gyucheol commented on src/modules/asset/components/AccelerateModal.tsx
> +          * 현재 설정하신 가스 가격이 낮아 요청하신 거래가 지연되고 있습니다.
4b7809d

2021-08-05 17:14 UTC, JUNG-gyucheol commented on src/modules/crypto/Detail.tsx
> +          const {isPendingTx, pendingTxs} = getPanadingTx(transactions, newTxs, '', asset.type);
6549845

2021-08-05 17:15 UTC, JUNG-gyucheol commented on src/utiles/pendingTransaction.ts
> +  let isPendingTx = 0;
5fa9c52

2021-08-05 17:17 UTC, JUNG-gyucheol commented on src/utiles/pendingTransaction.ts
> +export const changeTxStatus = (
어떻게 분리 할 지를 잘 몰라서 일단은 컴포넌트안에서 분리하고 함수로 만들지 않았습니다.
e76e4ba

2021-08-05 17:18 UTC, JUNG-gyucheol commented on src/modules/asset/components/TransactionItem.tsx
> +              moment(transaction.createdAt).format('YYYY-MM-DD') +
878a265

2021-08-05 17:19 UTC, JUNG-gyucheol commented on src/modules/asset/Purchase.tsx
> +      waitTxResult(contractAddress, 2); // status는 enum-pending으로 변경
e8d8741

2021-08-06 02:37 UTC, donguks commented on src/modules/asset/components/TransactionItem.tsx
> +      const isCrytoELA = paymentMethod !== 'NONE';
ㅋㅋㅋ 음 이게 두번 요청하면 정확히 해결되는건가요?! 뭔가 억지로 맞춰주는 듯한 느낌입니다. 혹시 다른 방법은 없을까요?!

2021-08-06 02:39 UTC, donguks commented on src/utiles/pendingTransaction.ts
> +export const getPanadingTx = (
넵 뭔가 이름은 대기중인 트랜잭션만 리턴할 것 같은데, boolean 값도 같이 리턴하니 헷갈릴 수 있을 것 같아요! 더 좋은 이름이 없을지...

2021-08-06 02:58 UTC, donguks commented on src/modules/asset/Purchase.tsx
> +            value: utils.parseEther('0.00001'), // 현재 가지고 있는 자산만큼 넣어주자
ㅋㅋㅋ 코멘트 잘봤습니다. 유저가 입력하는 input을 넣어주는게 제일 좋긴합니다.

2021-08-06 02:58 UTC, donguks commented on src/modules/asset/components/TransactionItem.tsx
> +      const re = await txRes?.wait();
앗! 여기서 txRes를 기다리는 코드가 있었군요!!
코반이라면 네트워크속도가 빨라서 괜찮았겠지만, 이더리움 메인넷은 더 올래걸립니다. 
만약 오래걸리면 버튼을 누른채 기다리게 되는거죠?? 
여기도 TransactionContext에서 tx를 완료로 바꿔주면, 상태값을 자연스레 업데이트해주도록 구현하면 될것 같습니다.

2021-08-06 02:58 UTC, donguks commented on src/modules/asset/components/TransactionItem.tsx
> +      const re = await txRes?.wait();
https://github.com/elysia-dev/dutch/blob/master/src/modules/crypto/Detail.tsx#L177-L190 여기를 참고해주시면 될것 같아요! TranscationProvider에 넣어주기만 하면 알아서 pending을 기다려주고 완료되면 기다려줍니다.

2021-08-06 02:58 UTC, donguks commented on src/modules/asset/components/TransactionItem.tsx
> +  const { addPendingTransaction } = useContext(TransactionContext);
트랜잭션 아이템이 너무 많은 것을 하는 것 같아요! 트랜잭션 아이템을 여러개 랜더되기 때문에 이렇게 많은 변수를 선언하면 성능 이슈도 있을 것 같습니다. speedUp의 함수를 재활용이 가능하도록 hooks 형태로 만든 뒤, 상품 구매페이지와 자산상세페이지에서 hooks를 사용하도록 하면 더 좋을 것 같습니다! 요런식으로 만들수 있습니다. 
https://github.com/elysia-dev/dutch/blob/master/src/hooks/useWatingTx.ts

2021-08-09 17:41 UTC, JUNG-gyucheol commented on src/utiles/pendingTransaction.ts
> +export const getPanadingTx = (
395ee5d 33a4849
boolean 값은 따로 분리 했습니다.

2021-08-09 17:42 UTC, JUNG-gyucheol commented on src/modules/asset/components/TransactionItem.tsx
> +      const isCrytoELA = paymentMethod !== 'NONE';
7e5216f

2021-08-09 17:46 UTC, JUNG-gyucheol commented on src/modules/asset/components/TransactionItem.tsx
> +  const { addPendingTransaction } = useContext(TransactionContext);
7e5216f
이게 hooks가 맞는지 모르겠는데 일단 구현은 해봤습니다.

2021-08-10 02:35 UTC, JUNG-gyucheol commented on src/modules/asset/Purchase.tsx
> +            value: utils.parseEther('0.00001'), // 현재 가지고 있는 자산만큼 넣어주자
estimate 값이 잘 안나와서 '0.1' 로 설정을 해놓았습니다.

2021-08-10 02:36 UTC, JUNG-gyucheol commented on src/modules/asset/Purchase.tsx
> +            value: utils.parseEther('0.00001'), // 현재 가지고 있는 자산만큼 넣어주자
813dbc9

2021-08-11 04:10 UTC, JUNG-gyucheol commented on src/hooks/useTransferTx.ts
> +  useEffect(() => {
usestate는 지우고 함수로 변경했습니다.
9e40818

2021-08-16 12:20 UTC, donguks requested changes
몇가지더 리팩토링할만한것들이 보입니다! 한번에 제가 다 볼 수 있으면 좋겠는데 코드를 이해하는데 생각보다 시간이 걸려 리뷰를 반복적으로하면서 더 좋은 개선점이 보이는것 같습니다. 제가 작성한 코드도 썩 좋지 못해서 요렇게 코드를 개선의 여지가 많은 코드를 작성하게 되는것 같아 마음의 짐이 있네요ㅜㅜ! 이제 진짜 정말 얼마 안남았습니다. 몇 안되는 함수 리팩토링하고 바로 머지하죠!!

2021-08-16 12:20 UTC, donguks commented on src/modules/asset/components/TransactionItem.tsx
> +      if (
조건문이 많은 경우는 if~else를 복잡하게 하는 것보다는, case문을 사용하는 편이 낫습니다.

2021-08-16 12:20 UTC, donguks commented on src/modules/asset/components/TransactionItem.tsx
> +  const getEstimateGas = async (text: string) => {
이 함수가 해주는게 너무 많은 것 같아요! 분리하고 줄여보는것은 어떨까요?
text 값을 점검하는고, 특정 숫자보다 크면 ui를 disable시키고, gas비를 추정후, gas값을 수정합니다.
총 4가지의 일을 하는데, text를 점검하는하는 역할은 충분히 분리가 가능할 것 같아요.
특정 ui를 diasble하는 것은 disable이라는 상태를 따로 정의하지 않고 해당 변수값이 필요한곳에서 직접 조건문을 넣는것은 혹시 가능할까요??
gas비용을 추정하는 건 따로 함수로 분리해도 괜찮을 것 같습니다.

2021-08-16 12:20 UTC, donguks commented on src/modules/asset/components/TxInput.tsx
> +    // useEffect(() => {
아! 아예 로딩인디케이터를 지웠군요. 그럼 아래 코드를 코멘트로 남기지말고 그냥 지워주세요!!
@leegakyeong 이거 아이폰은 로딩인디케이터가 보이지 않는 이슈가 있어서 요렇게 처리했던거죠?? Overlay가 사라지고 다른 방식으로 로딩을 보여주도록 이 풀리퀘스트에서 변경된듯 합니다.

2021-08-16 12:20 UTC, donguks commented on src/modules/crypto/Detail.tsx
> +      pendingTxs.concat(notPendingTxs);
concat은 pendingTxs에 notPendingTxs를 붙인 array를 리턴해줄텐데, 따로 pendingTxs를 수정하는게 아니므로, 이렇게 선언하면 아무런 의미가 없는 코드인것 같습니다. 지워도 좋을 것 같아요.

2021-08-16 12:20 UTC, donguks commented on src/modules/crypto/Detail.tsx
> +    const pendingTxs = transactions.filter(
pendingTx라서 pending일 상태만 filter하는 것 처럼 보이는데, cryptoType까지 || 조건으로 체크하는 이유가 있나요!?! 이 코드의 논리가 궁금합니다! 또한 코드를 읽어보면 대기중인 트랜잭션으로 sort하는 것과 같은 효과를 만드는 것 처럼 보여서, 두가지로 필터 후 붙이지 않아도 될것 같은데, 혹시 sort랑은 좀 다를까요??

2021-08-16 12:20 UTC, donguks commented on src/utiles/createTransferTx.ts
> +  addPendingTransaction: (
hooks로 구현했으면 addPendingTransaction함수를 인자로 넘기지 않았어도 되었을 텐데, 우선 이 함수는 이렇게 마무리하는걸로하죠!

2021-08-18 01:27 UTC, JUNG-gyucheol commented on src/modules/asset/components/TransactionItem.tsx
> +  const [updateGasPrice, setUpdateGasPrice] = useState('1');
617bbc1

2021-08-18 01:27 UTC, JUNG-gyucheol commented on src/modules/asset/components/TransactionItem.tsx
> +  const getEstimateGas = async (text: string) => {
9b931b4

2021-08-18 01:28 UTC, JUNG-gyucheol commented on src/modules/asset/components/TransactionItem.tsx
> +    }
36cfc1f

2021-08-18 01:30 UTC, JUNG-gyucheol commented on src/modules/asset/components/TransactionItem.tsx
> +  const getEstimateGas = async (text: string) => {
함수를 따로 만들어서 다 분리 시켜서 호출을 하였습니다.
f49e32f

2021-08-18 01:32 UTC, JUNG-gyucheol commented on src/utiles/createTransferTx.ts
> +  addPendingTransaction: (
시간이 있을 때 생각해서 바꿔보겠습니다. 함수에 전달인자도 너무 많이 들어가고 해서 다시 바꿔야할 부분이 많다고 생각합니다.

2021-08-18 01:35 UTC, JUNG-gyucheol commented on src/modules/crypto/Detail.tsx
> +    const pendingTxs = transactions.filter(
생각해보니 crytotype까지 조건 줄 필요는 없었네요. 전에 상품상세페이지에서 같이 쓰다보니 넣어버렸네요.

2021-08-18 04:06 UTC, JUNG-gyucheol commented on src/modules/asset/components/TxInput.tsx
> +    // useEffect(() => {
로딩인디케이터 부분은 삭제했습니다. 지금은 구매하기 버튼을 눌렸을 시에 이전페이지로 돌아가도록 구현 해놓았습니다. 
다음 스프린트 때 어떻게 표시해야 할 지 정하면 좋을 것 같습니다. 더 좋은 방법이 있으면 바로 수정하도록 하겠습니다.

2021-08-18 08:50 UTC, donguks commented on src/modules/asset/components/TxInput.tsx
> +    // useEffect(() => {
넵 우선은 요렇게 진행하고, 다음 작업에서 개선하면 될것 같아요!

2021-08-18 08:52 UTC, donguks approved these changes
고생하셨습니다!
이제는 코드가 많이 다듬어진것 같아용~
conflic해결하고 머지해주시면 될것 같습니다!

2021-08-19 02:44 UTC, merged