스테이킹 UI에 데이터 추가
elysia-dev/dutch pull request #54
Opened 2021-08-10 09:26 UTC by leegakyeong

## 한 일
* 스테이킹풀 컨트랙트 함수 추가 (아직 엘리파이에서처럼 클래스로 빼지는 못했습니다..!)
* 메인 화면의 스테이킹 관련 컴포넌트 & 스테이킹 관련 페이지에서 더미 데이터를 빼고 컨트랙트로 받아온 실제 테스트 데이터를 보여 줌

2021-08-16 13:02 UTC, donguks requested changes
넵! 가경님의 깔끔한 코드 잘 확인했습니다. 
몇가지 반복되는 조건문들이랑, 리팩토링 요소만 적용하면 바로 머지해도될것 같아요!
고생하셨습니다.

2021-08-16 13:02 UTC, donguks commented on src/modules/staking/CurrentDashboard.tsx
> +    !currentRound ||
앗 여기 조건문이 어디서 많이 본것 같군요 ㅎㅎ
왠지 enum으로 대기중, 끝남, 진행중? 세가지 상태로 정의하고 현재 무슨 상태인지 리턴하는 함수를 만든다면 비슷한 조건문들을 줄여볼 수 있을 것 같습니다!

2021-08-17 06:18 UTC, leegakyeong commented on src/modules/dashboard/components/StakingListing.tsx
> +const StakingListing: React.FC<{ user: any; isWalletUser: boolean }> = ({
앗 그러게요... 제가 왜그렇게했을까요..?!?! context로 받아오도록 수정했습니다! 02cc5e17e75ed9e1b0bf2a53c8c58a1f8a0f1482

2021-08-19 02:50 UTC, leegakyeong commented on src/modules/dashboard/components/StakingListing.tsx
> +          const stakingAmount = res[2].toNumber(); // principal
일단 res 관련된 부분부터 말씀드리면 res가 이렇게 생긴 배열로 오더라구요! 그리고 키는 없어서(res.userPrincipal이라고 하면 undefined가 나옵니다) 이 부분은 그대로 둬도 될 것 같습니다! 
```shell
Array [
  Object {
    "hex": "0x00",
    "type": "BigNumber",
  },
  Object {
    "hex": "0x00",
    "type": "BigNumber",
  },
  Object {
    "hex": "0x00",
    "type": "BigNumber",
  },
]
```

2021-08-19 04:32 UTC, leegakyeong commented on src/modules/dashboard/components/StakingListing.tsx
> +          const stakingAmount = res[2].toNumber(); // principal
BigNumber 관련된 부분은 06a58a7f8ebac70c68b1b4488423ab03f494bb62 이렇게 고쳤는데 최선인지는 모르겠네요,,, 확인 부탁드립니다!!

2021-08-19 05:23 UTC, leegakyeong commented on src/modules/staking/CurrentDashboard.tsx
>  const DashBoard: React.FC<{ route: any; navigation: any }> = ({ route }) => {
앗 useRoute를 쓸 수 있다는 사실은 처음 알았네요!! 저 navigation prop은 쓰지도 않으면서 왜 받았는지 모르겠네요..ㅋㅋㅋ 아무튼 동욱님이 말씀해 주신 대로 고쳤습니다! 3f7da9d1bba35f28cde76fe0c9f870e5bd1acab8

2021-08-19 05:34 UTC, leegakyeong commented on src/modules/dashboard/components/StakingListing.tsx
> +        contract?.getUserData(round, userAddress).then((res: any) => {
이거는 메인 페이지에서 라운드별로 유저가 스테이킹한 금액이 있는지 확인한 다음 금액이 있으면 스테이킹과 보상 수량을 보여 주는 컴포넌트라서 일단은 모든 라운드의 데이터를 다 받아오는 게 맞는 것 같습니다! 이 페이지에는 라운드를 변경하지 않아서요! 밑에 주석 처리한 부분은 일단 테스트용으로 모든 라운드를 다 보여 주던 거라서 그 부분은 업데이트했습니다! dd05b549456222ca81bc694e447b0494d92fc0dd 
![image](https://user-images.githubusercontent.com/22510942/130013024-4b82a2a7-9a35-4da5-bdb7-74e364296b0c.png)

2021-08-19 07:07 UTC, leegakyeong commented on src/utiles/calculateAPR.ts
> +    return '∞';
constants.MaxUint256 가 78자리더라구요! 그런데 엄청 긴 숫자가 사용자 눈에 보이는 기간이 얼마나 될지 잘 몰라서 일단 1조까지 포맷팅해봤는데 괜찮을까요? ca0bb66d25669ae60ff7e80a055419cb9fc1a837

그리고 이건 좀 부가적인 건데 만약에 APR이 1234%일 때 1K로 보여 주는 건 너무 부정확한 숫자일까요...? 아니면 상관없을까요?! 인스타그램 같은 데서는 1.23K 이런 식으로도 표기했던 것 같아서요! 엘리파이에서도 1K로 보여주는 거면 상관 없지만 그냥 APR 수치가 얼마나 중요한 건지 궁금하기도 해서 여쭤봅니다!

2021-08-19 10:42 UTC, leegakyeong commented on src/modules/staking/components/DotGraph.tsx
> +  function getDotStatus(dotRound: number) {
적어 주신 삼항연산자보다는 조금 더 복잡한 경우인 것 같습니다! dotRound와 currentRound가 같더라도 해당 라운드가 이미 종료된 상태(하지만 다음 라운드는 아직 시작하지는 않은 상태)일 수도 있어서요. 대신 라운드 상태에 대한 코드를 맨 마지막 코멘트에서 스테이킹 상태에 대해 제안해 주신 것과 비슷하게 바꿔 보았습니다! 
4985837682a1ee1a8919ddec250c87ec73ed9ba1

2021-08-19 10:42 UTC, leegakyeong commented on src/modules/staking/CurrentDashboard.tsx
> +    nextButtonDisabled = true;
e05760b867962926e1052612e9dd2a16f0faf12c 아래 코멘트와 같은 커밋에서 수정했습니다!

2021-08-19 10:42 UTC, leegakyeong commented on src/modules/staking/CurrentDashboard.tsx
> +    !currentRound ||
이렇게 수정해 봤는데 어떨까요..?? e05760b867962926e1052612e9dd2a16f0faf12c

2021-08-20 01:27 UTC, donguks commented on src/modules/dashboard/components/StakingListing.tsx
> +          const stakingAmount = res[2].toNumber(); // principal
넵 확인했습니다. 
여기 나중에 typechain사용하면 좀 더 쉽게 사용할 수 있습니다. 
https://github.com/elysia-dev/elyfi-web/blob/535c263fd31030c33bcf3a2e11b2e39175938499/src/containers/Staking.tsx#L93-L102
(저 코드에 user, account 혼용이 있는데 무시해주세요ㅎㅎ 아마 web3의 account와 stakingPool의 userData가 섞여있는듯 합니다..)
우선 여기까지 마무리해도괜찮을 것 같습니다.

2021-08-20 01:29 UTC, donguks commented on src/utiles/calculateAPR.ts
> +    return '∞';
네네 소수점 두자리도 보여주는게 더 좋을 것 같습니다! 엘리파이에서도 두번째 자리까지는 보여줍니다. 예전에 초기 이자가 높을때도 그렇게 표현했었어요!
<img width="1221" alt="스크린샷 2021-08-20 오전 10 30 35" src="https://user-images.githubusercontent.com/69144981/130164663-23b8ee2b-3689-4c41-b162-2d49f76175bb.png">

2021-08-20 01:29 UTC, donguks commented on src/modules/staking/components/DotGraph.tsx
> +  function getDotStatus(dotRound: number) {
네네 훨씬 보기좋아졌군요!

2021-08-20 01:30 UTC, donguks commented on src/modules/staking/CurrentDashboard.tsx
> +    !currentRound ||
네! 좋습니다

2021-08-20 01:32 UTC, donguks approved these changes
고생하셨습니다!

2021-08-20 02:36 UTC, leegakyeong commented on src/utiles/calculateAPR.ts
> +    return '∞';
3c67869c93c5e2d20d2e76332e8aa9597d11ccdb

2021-08-20 07:37 UTC, merged