앱 내 지갑 스테이킹 기능  (진행중)
elysia-dev/dutch pull request #57
Opened 2021-08-19 03:09 UTC by JUNG-gyucheol

2021-08-20 01:33 UTC, donguks commented
지금 가경님 브랜치가 머지되는 걸 기다린 후 리뷰 진행할게요! 작업내용이 섞여있네요.

2021-08-23 04:55 UTC, donguks requested changes
코드 확인 잘?했습니다!

master브랜치에 가경님 브랜치가 들어갔는데도! 여전히 이 풀리퀘스트에 가경님 작업이 많이보이네요 ㅜ 나름 규철님 코드만 확인한다고 노력했는데 잘되었는지 모르겠습니다.
typechain을 사용하긴 하셨는데, 여전히 stakingpool abi가 남아있어서 반쪽짜리로만 사용하신것 같습니다ㅜ 반복되는 것들은 hooks로 정의해서 재활용하고, type-chain을 이용해서 abi 파일을 지워보는것은 어떨까요?!

고생하셨습니다!

2021-08-23 04:55 UTC, donguks commented on src/hooks/useEstimateGas.ts
> +import { StakingPool } from '@elysia-dev/contract-typechain';
hooks를 이용해서 staking contract의 gas비 추정하는 것 좋습니다!
stakingPoolContract만 확인하는거니, 이름을 더 구체적으로 만들어주면 좋을것 같아요~

2021-08-23 04:55 UTC, donguks commented on src/hooks/useStakingByType.ts
> +  const initStaking = async (
initStaking 보다 더 좋은 이름이 없을까요?!

2021-08-23 04:55 UTC, donguks commented on src/hooks/useStakingByType.ts
> +  const unStake = async (value: string, round: number) => {
unStake, stake, migrate 등의 함수는 이 hooks에서 리턴하는게 아니고, 코드 양도 많지않아 initStaking에 포함시켜도 좋을것 같습니다.

2021-08-23 04:55 UTC, donguks commented on src/hooks/useStakingInfo.ts
> +  stakingPoolContract: StakingPool,
StakingPool을 인자로 받지 않고, 컨트랙트 자체를 내부에 선언해도 좋을것 같아요~

2021-08-23 04:55 UTC, donguks commented on src/hooks/useStakingInfo.ts
> +  const [principal, setPrincipal] = useState<number>(0);
principal, reward를 하나의 state로 묶어도 괜찮을 것 같습니다.

2021-08-23 04:55 UTC, donguks commented on src/modules/staking/Reward.tsx
> +  const stakingPoolContract = getStakingPoolContract(stakingAddress, signer);
getStakingPoolContract을 사용하지 않아도됩니다!
getContract는 ABI파일이 필요한데, type-chain을 이용하면 필요없습니다!
elyfi-web의 경우 컨트랙트는 hooks로 선언하고 재사용했습니다! 여기서도 비슷한 원리로 사용할 수 있을 것 같아요!
https://github.com/elysia-dev/elyfi-web/blob/main/src/hooks/useStakingPool.ts

2021-08-23 04:55 UTC, donguks commented on src/modules/staking/Stake.tsx
> +  const { ercAddress, stakingAddress, signer } = {
변수를 차례대로 선언해도 괜찮을 것 같은데, 혹시 이렇게 object로 선언한 특별한 이유가 있을까요?!

2021-08-23 04:55 UTC, donguks commented on src/modules/staking/Unstake.tsx
> +  // const confirmationList = earnReward
사용하지 않는다면 코멘트는 지워주세요~

2021-08-23 04:55 UTC, donguks commented on src/modules/staking/UnstakeAndMigrate.tsx
> +  const { stakingAddress, signer } = {
위 코멘트에서도 적었지만, stakingPool을 사용하는 hooks를 만들어두면,
stakingAddress, signer등 요렇게 정의해서 사용하는 방식 자체를 재활용할 수 있습니다!

2021-08-23 04:55 UTC, donguks commented on src/utiles/getContract.ts
> +  return getContract(EL_STAKING_POOL_ADDRESS, StakingPoolAbi);
elyfi-web에서는 typechain을 적용한 후 getContract를 사용하는 패턴을 아예 제거할 수 있었습니다!
dutch에는 아직 asset-token이 남아있기때문에 staking contract정도만 적용해서 제가 과거에 정의해놓은 이상한 패턴사용은 줄일 수 있을 것 같습니다!

2021-08-23 05:42 UTC, JUNG-gyucheol commented on src/hooks/useStakingByType.ts
> +  const initStaking = async (
저도 이름이 이상하다고 생각해서 stakingByType으로 바꿔보았습니다.

2021-08-23 08:39 UTC, JUNG-gyucheol commented on src/utiles/getContract.ts
> +  return getContract(EL_STAKING_POOL_ADDRESS, StakingPoolAbi);
5b8e5bb

2021-08-23 08:40 UTC, JUNG-gyucheol commented on src/modules/staking/Stake.tsx
> +  const { ercAddress, stakingAddress, signer } = {
hooks로 전부 변경하고 선언한 변수들은 전부 지웠습니다.

2021-08-23 08:41 UTC, JUNG-gyucheol commented on src/hooks/useStakingInfo.ts
> +  const [principal, setPrincipal] = useState<number>(0);
8340e65

2021-08-23 08:43 UTC, JUNG-gyucheol commented on src/hooks/useStakingByType.ts
> +  const unStake = async (value: string, round: number) => {
7548b10

2021-08-23 08:47 UTC, JUNG-gyucheol commented
65bfec5 : stakingpool 컨트랙트 hooks
1000d76 : Erc20 컨트랙트 hooks
20e3052 : estimategas hooks 변경
7548b10 : useStakingByType hooks 변경

2021-08-24 05:34 UTC, JUNG-gyucheol commented
APR 계산하는 부분은 elyfi-web 부분 보고 다시 수정했습니다.

2021-08-24 05:58 UTC, donguks approved these changes
사소한것들 수정하고, conflict를 해결 후 머지해도될것 같습니다.

2021-08-24 05:58 UTC, donguks commented on src/abi/StakingPoolAbi.json
> +[
이제 이 파일은 지워도 되지않을까요!

2021-08-24 05:58 UTC, donguks commented on src/modules/staking/Reward.tsx
> +                console.log('보상 수령 해야 함 (외부 지갑 유저)');
console 지워주세요~

2021-08-24 07:46 UTC, leegakyeong commented
나중에 StakingInfoBox 컴포넌트 자체는 StakingListing 안으로 다시 옮겨주시고 StakingListing에는 값만 넣어주는 걸로 바꿔주세요~~

2021-08-24 07:55 UTC, merged