버그 수정
elysia-dev/dutch pull request #66
Opened 2021-08-27 10:08 UTC by JUNG-gyucheol

- 마이그레이션에서 언스테이킹 입력창에 0입력 가능하도록 설정
- 최종확인창에서 value 값에 소수점 적용
- 스테이킹 트랜잭션 성공 후에 업데이트 되도록 구현
- approve 후 가스한도가 바로 안나와서 approve 성공 후 1초 주기로 가스비를 조회합니다.

2021-08-30 09:52 UTC, donguks requested changes
잘봤습니다!
retry 횟수를 제한해주는게 좋을 것 같아요!

2021-08-30 09:52 UTC, donguks commented on src/modules/staking/Stake.tsx
> +    if (estimateGasCount === 0) return;
이렇게 두면 성공할때까지 gas Estimation을하는거라 혹시 버그있으면 무한으로 돌 수 도 있을 것 같은데, try를 3번정도로 제한하는건 어떠신가요~

2021-08-30 22:40 UTC, JUNG-gyucheol commented on src/modules/staking/Stake.tsx
> +    if (estimateGasCount === 0) return;
a337242

2021-08-31 01:57 UTC, donguks approved these changes

2021-08-31 03:26 UTC, merged