approve 화면 개선
elysia-dev/dutch pull request #68
Opened 2021-09-02 07:10 UTC by JUNG-gyucheol

- approve ui 작업
- approve 버튼 클릭시 트랜잭션 처리중이라는 로딩인디케이터 표시
- 상품화면에서도 구매하기 버튼 눌렸을 시에 버튼에 로딩인디케이터 표시
- 상품 구매페이지에서 approve 후 예상가스비 업데이트

2021-09-03 05:39 UTC, donguks requested changes
사소한것들 고치고, 번역내용추가하고, 재활용성만 높여주면 될것 같습니다. 
고생하셨습니다! 이번 작업 들어가면 승인과정에서 유저 경험이 많이 개선될것 같아 기대가됩니다 ㅎㅎ

2021-09-03 05:39 UTC, donguks commented on src/i18n/ko.json
>        "accelerate_gas_fee": "가속화 수수료",
번역 작업이 남아있군요!!

2021-09-03 05:39 UTC, donguks commented on src/modules/asset/Purchase.tsx
> +    if (estimateGasCount === 0 || estimateGasCount >= 4) return;
이미 예전에도 사용한 논리인것 같은데! 혹시 재활용이 가능할까요~?

2021-09-03 05:39 UTC, donguks commented on src/modules/staking/Stake.tsx
> +                '1' + '0'.repeat(30),
ㅋㅋㅋ 여기 [ethers.Constant.UnitMax256 ](https://docs.ethers.io/v5/api/utils/constants/#constants-MaxUint256) 사용해주시면 더 좋을 것 같습니다!

2021-09-03 05:39 UTC, donguks commented on src/modules/staking/Stake.tsx
> +      console.log('실행');
console.log는 지워도 될것 같습니다.

2021-09-03 05:39 UTC, donguks commented on src/modules/staking/Stake.tsx
> +        if (estimateGasCount >= 3) {
여기 gasCount 사용하는 논리도 다른곳에서 이미 사용하고 있는데 재활용할 수 있을것 같아요!!

2021-09-03 05:39 UTC, donguks commented on src/modules/asset/Purchase.tsx
> +        '1' + '0'.repeat(30),
여기도 Constants 사용하면 좋을것 같습니다

2021-09-06 08:16 UTC, JUNG-gyucheol commented on src/modules/asset/Purchase.tsx
> +    if (estimateGasCount === 0 || estimateGasCount >= 4) return;
d59e2df

2021-09-07 03:12 UTC, donguks requested changes
거의 다왔습니다!
이름 정도, 함수 인자정리? 요정도만하고 마무리해도될것 같아요.
고생하셨습니다!

2021-09-07 03:12 UTC, donguks commented on src/hooks/useCount.ts
> +const useCount = (
뭔가 더 좋은 이름이 있을것만 같습니다.
얼마나 적극적으로 재활용하느냐에 따라 이름이 다를것 같아요.
## 1. 소극적인 재사용
여러번 실행해주니까 useMultipleTry? 느낌으로 바꿔보면 좋을것 같습니다. 
또한 인자의 경우 더 다양한곳에서 사용할 수 있도록 handler, onFinally?(이름은 수정해주세용)로 인자를 나눠서 handler에는 setEstimate(stakingType)을 실행하는 arraow function 자체를 넣고, onFinally에는 setIsApproved(true); setIsLoading(false); 두개를 실행하는 함수를 만들어봐도 좋을 것 같습니다.

## 2. 더 적극적으로 재사용
useCount는 너무 일반적이고, 가스비를 추정하는데 도움을 주는 함수니 useEstimateGas 뭔가 이런식으로 지어보면 좋을 것 같습니다. 
estimateGas 함수는 그대로 인자를 받고, approved, loading 상태값 자체도 이 hooks에 넣어서 관리하는게 어떨까요?! return해서 hooks를 사용하는 곳에서 approved, loading을 사용하면 되긴합니다. 다만 setApproved, setLoading을 어디선가 써야한다면 위 방법이 더 좋을것 같긴해요!

1안 2안 중 선택해서 작업진행해주세요~

2021-09-07 03:12 UTC, donguks commented on src/hooks/usePurchaseGas.ts
> +const usePurchaseGas = (
"useEstimatedPurchaseGas" 로 써보면 더 구체적이라 좋을것 같습니당. 요 재사용은 hooks로 잘 작성하신것 같아요!!

2021-09-10 03:37 UTC, leegakyeong requested changes
리뷰 완료했습니다!! 제가 이번 풀리퀘스트 읽으면서 생각한 개선하면 좋을 점은 크게 두 가지인 것 같습니다. 둘 다 가독성과 관련된 사항인 것 같은데, 논리나 기능적인 부분들은 동욱님이 이미 짚어 주셨고 제가 첨언할 내용이 별로 없기도 해서요! 

1. 좀 길어지라도 내용을 정확하게 표현하는 이름으로 짓기
2. 변수 이름은 명사구로, 함수 이름은 동사구로 짓기

저희끼리는 사실 이제 코드를 어느 정도 아니까 이름이 엄청 자세하지 않아도 거의 다 알아들을 수 있지만, 먼 훗날에 코드를 다시 보게 되거나 새로운 개발자분이 들어오시는 상황을 생각해 보면 처음부터 좀 더 신경써서 지으면 더 편할 것 같아요!

참고하면 좋을 링크들도 몇 개 검색해서 첨부합니다. 
* [\[좋은 코딩 습관\] 깔끔한 코드 짜는 10가지 규칙](https://blog.naver.com/PostView.nhn?blogId=sooftware&logNo=221846090355&categoryNo=0&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=1&from=postView)
* [2. 변수명과 함수명 짓기](https://dkje.github.io/2020/08/03/CleanCodeSeries2-copy/)
* [Bool 변수 이름 제대로 짓기 위한 최소한의 영어 문법](https://soojin.ro/blog/naming-boolean-variables)

저도 뭐 변수명 명사로 하는 거 까먹기도 하고 마땅한 이름이 생각나지 않아서 대충 짓는 경우도 있지만... 그런 것도 앞으로 코드리뷰하면서 서로서로 고쳐주면 좋을 것 같습니다!!!

2021-09-10 03:37 UTC, leegakyeong commented on src/modules/asset/Refund.tsx
> +        productRefund={PurposeType.Refund}
`productRefund`에 들어가는 값이 `PurposeType.Refund`밖에 없는 것 같은데, 이 부분을 `isRefund={true}` 이런 식으로 바꾸면 어떨까요??

2021-09-10 03:37 UTC, leegakyeong commented on src/hooks/useCount.ts
> +  const setAddCount = () => {
`set`과 `add`가 둘 다 동사라서 이름이 약간 헷갈리는 것 같아요. 함수 내용을 보면 이름을 그냥 `addCount`라고 해도 될 것 같은데 혹시 어떻게 생각하시나요?!

2021-09-10 03:37 UTC, leegakyeong commented on src/modules/staking/Stake.tsx
>    const [isApprove, setIsApprove] = useState(true);
여기 `[isApproved, setIsApproved]`여야 하는데 오타가 난 것 같습니다!

2021-09-10 03:37 UTC, leegakyeong commented on src/modules/staking/Stake.tsx
>    const [estimateGasCount, setEstimateGasCount] = useState(0);
이름을 `[gasEstimationCount, setGasEstimationCount]` 이렇게 바꾸면 어떨까요?

2021-09-10 03:37 UTC, leegakyeong commented on src/modules/asset/Purchase.tsx
> +  const [approveGasPrice, setApproveGasPrice] = useState('');
이 변수가 approve하는 데 필요한 가스비를 지칭하는 거 맞나요?! 이 부분 이름을 `[approvalGasPrice, setApprovalGasPrice]`로 바꾸면 어떨까요?

2021-09-10 05:36 UTC, donguks commented
@leegakyeong 저보다 더 상세하게 리뷰를 남겨주셨군요! 감사합니다~

2021-09-13 01:34 UTC, donguks requested changes

2021-09-13 01:34 UTC, donguks commented on src/hooks/useBoolean.ts
> +function useBoolean(
더 구체적이고 좋은 이름이 있을 것 같아요...
useBoolean은 너무 일반적인 이름이고 useIsERC20 ? 과 같은 이름이 있을 것 같은데..!

음, 제 생각에는 hooks로 이렇게 간단한 논리를 재사용하는건 오버 엔지니어링인것 같아요.
isERC20과 같은 utils를 하나 만들어두는게 나을 것 같습니다.

2021-09-15 08:45 UTC, merged