그래프 데이터 수정
elysia-dev/dutch pull request #69
Opened 2021-09-02 09:34 UTC by JUNG-gyucheol

- 최근 거래가 없는 경우 데이터 50개이하로 그래프를 표시
최근 거래가 없을 때 거래날짜 기준으로 잡으려니 데이터가 안나오는 경우가 생길 것 같아서  트랜잭션 리스트에서 위에서부터 50개의 데이터로 그래프를 표시하도록 했습니다.

2021-09-10 06:01 UTC, donguks requested changes
코드의 논리자체는 괜찮은것 같은데, 코드를 좀더 개선할 수 있을 것 같아요!

2021-09-10 06:01 UTC, donguks commented on src/utiles/ChartTransactions.ts
>  export class ChartTransactions {
ChartTransactions class로 정의해야하는지 한번 더 고민해봐야할 것 같아요. 
class안에 들고 있는 member 변수들, 함수들의 재활용성이 높다면 class로 정의해도 괜찮을 것 같은데 현재의 경우 결국 사용하는 함수는 getResentTransactionChart 뿐인것 같아서요! 코드가 복잡해 질것 같아 일부러 부분부분 나눠둔 것 같은데, 제 생각에는, 재활용성이 있는게 아니라면 이렇게 나누지는 않아도될것 같아요. 오히려 이렇게 구현해서 xyDayValue 변수를 global 변수처럼 사용하게 되었는데, 가독성이라던가, 나중에 디버깅하기 어려운 지점이 될 가능성이 높아 보입니다.

2021-09-10 06:01 UTC, donguks commented
버그가있습니다! bnb 그래프 페이지에 가면 요렇게 undefined로 나오게됩니다.
![image](https://user-images.githubusercontent.com/69144981/132807180-5cd824e2-d6e5-4362-84d0-c3ad21a6c3c5.png)

2021-09-13 07:19 UTC, leegakyeong commented on src/modules/crypto/components/AssetGraph.tsx
> -          <ActivityIndicator size="large" color={lineColor} />
앗 ActivityIndicator 혹시 지우신 이유가 있을까요??

2021-09-13 07:19 UTC, leegakyeong commented on src/utiles/ChartTransactions.ts
> +    } else if (assetType === CryptoType.BNB || assetType === CryptoType.DAI) {
이 부분은 제가 다른 풀리퀘스트에서 ELFI_BLUE랑 DAI_YELLOW를 아예 추가해 놨어요! 나중에 충돌난 거 수정할 때 다시 얘기해 봅시당

2021-09-13 07:22 UTC, leegakyeong commented on src/modules/crypto/Detail.tsx
> +        await chartTransactions.getResentTransactionChart(
혹시 Recent의 오타 아닐까요?? 근데 제 생각에는 recent가 아닌 경우가 없으니 굳이 recent라는 형용사를 추가하지 않아도 될 것 같아요..! 그리고 이 변수명 외에도 resent로 오타난 다른 변수들이 더 있어서 확인 부탁드립니다!!

2021-09-13 16:10 UTC, JUNG-gyucheol commented on src/modules/crypto/components/AssetGraph.tsx
> -          <ActivityIndicator size="large" color={lineColor} />
로딩인디케이터 이중으로 표시가 되서 지워버렸습니다.

2021-09-14 04:46 UTC, donguks approved these changes
고생하셨습니다!

2021-09-15 00:46 UTC, leegakyeong commented on src/modules/crypto/components/AssetGraph.tsx
> -          <ActivityIndicator size="large" color={lineColor} />
이제 자산 디테일 페이지 로딩할 때 로딩인디케이터 대신 스켈레톤을 쓰게 돼서  이 부분은 남겨놓았으면 합니다!

2021-09-15 08:44 UTC, merged