메인대쉬보드 elfi 스테이킹 조회 버그 수정
elysia-dev/dutch pull request #80
Opened 2021-09-28 04:14 UTC by JUNG-gyucheol

- useStakingPool 파일에서 함수를 추가했습니다.

production 환경에서 외부지갑으로 테스트 부탁드립니다. 
내부지갑으로 스테이킹, 언스테이킹은 테스트 완료하였습니다.

2021-09-28 06:04 UTC, donguks requested changes
단순한 버그인데 변경점이 너무 많습니다.
실제 버그가 어떤 원인인지 공유해주시면 더 좋을 것 같습니다. 
ELFI 스테이킹에서 v1조회시 컨트랙트 주소가 잘못된건지, 아니면 데이터를 잘못 만들고 있는건지 지금 코드로만 보기에는 동일한 논리를 수행하는 코드같아보여서요!

또한 지금보니 컴포넌트를 상태값에 넣어두고 있는데 별로 좋은 패턴이 아니고 자주 쓰이지도 않습니다. 왜냐하면, 디버깅할때 상태값을 데이터로 설정해두었다면 상태값을 확인하면 쉬운데, 데이터가 아니고 컴포넌트라서 그 값을 로그로 확인하는게 어렵기 때문입니다 ㅜㅜ 지난번 코드리뷰에서 놓쳤던 문제같군요! 나중에 리팩토링해주세요!

2021-09-28 06:04 UTC, donguks commented on src/hooks/useStakingPool.ts
> +  const setContract = (type?: CryptoType, isV2?: boolean) => {
setContract, changeContract 둘다 뭔가 설정하거나 바꾸는 변수가 없어서 이름이 적절하지 않은 것 같아요. 차라리 getContract가 더 코드상 의미가 맞습니다.

2021-09-28 07:47 UTC, JUNG-gyucheol commented
v1 컨트랙트로 reward 함수를 실행시키지 못하는 상황이 생겨서 
1차 스테이킹을 조회할 때도 v2 contract로 실행됩니다.

2021-09-28 07:51 UTC, JUNG-gyucheol commented
v1 컨트랙트로 1차 스테이킹 조회 하는 동안 map 함수가 한 번에 4라운드까지 실행 돼서 1차 리워드 데이터를 실행 할 때부터 v2 컨트랙트가 실행됩니다. 
1차 리워드 / 2차 스테이킹/리워드를 데이터를 가져올 때는 v2 contract로 실행됩니다.
클로저 문제가 발생해서 스테이킹과 리워드 데이터를 가져오는 함수를 따로 만들었습니다.

2021-09-30 05:39 UTC, donguks approved these changes
넵! 확인했습니다. 훨씬 더 좋습니다 ㅎㅎ

2021-10-05 00:04 UTC, merged